### ISSUE TITLE
I am not getting cast icon

### ISSUE THREAD

**Issue by chaitanya508** [ferranponsscmspain/android-cast-remote-display-sample#4]
CastRemoteDisplayLocalService.getInstance() giving null value...

Please revertme as sson as posssible

Thank you. @ferranpons 
![second](https://cloud.githubusercontent.com/assets/18733999/25018573/3aeb1624-20a5-11e7-84f4-1c3e8f32448d.png)

**Comment by ferranpons** [comment]
@chaitanya508 sorry for replying so late. This project is not maintained, only serve as a sample. If you're having issues with the latest versions of the Android SDK I can't help you.

![sorry](https://media.giphy.com/media/3o85xHtQnF5qtOPPyg/giphy-downsized.gif?response_id=5920141a9543aa845d2d9b9a)

**Comment by arpu** [comment]
i have the same problem with the latest  master version

**Comment by arpu** [comment]
will try to debug this

**Comment by arpu** [comment]
anything more that i need to set? 
i have done add my appid to this  file 
https://github.com/ferranpons/android-cast-remote-display-sample/blob/master/app/src/main/res/values/strings.xml#L3

**Comment by arpu** [comment]
here is the logcat 
https://gist.github.com/arpu/6ecf851dd65f3b4ac773c5c435427a2d

@ferranpons  any idea whats going wrong?

**Comment by arpu** [comment]
looks like i had  entered the wrong serial number for the device test :/ 

now i see the cast button but on the device i only see the app name 
do i need a special html js receiver app?
